# Generated by Django 3.0.6 on 2020-06-24 13:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record', models.CharField(max_length=254, unique=True)),
                ('userId', models.UUIDField(default=uuid.uuid4)),
                ('recordedOn', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
