# Generated by Django 3.0.6 on 2020-06-24 13:32

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompteUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('solde', models.DecimalField(decimal_places=2, max_digits=7)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now=True)),
                ('date_activation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_expiration', models.DateTimeField(default=django.utils.timezone.now)),
                ('nom_forfait', models.CharField(default='aucun forfait', max_length=25)),
                ('userId', models.UUIDField(default=0, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Forfait',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=26, unique=True)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=8)),
                ('expire_days', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
