# Generated by Django 3.0.7 on 2020-07-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biling_and_payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compteuser',
            name='userId',
            field=models.UUIDField(unique=True),
        ),
    ]
