# Generated by Django 3.0.7 on 2020-07-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biling_and_payment', '0002_auto_20200713_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compteuser',
            name='userId',
            field=models.UUIDField(),
        ),
    ]
