# Generated by Django 3.0.7 on 2020-06-23 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='kind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='users_crud.DeviceType'),
        ),
        migrations.AddField(
            model_name='userprofil',
            name='devices',
            field=models.ManyToManyField(to='users_crud.Device'),
        ),
    ]
