# Generated by Django 3.0.7 on 2020-06-23 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_crud', '0002_auto_20200623_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofil',
            name='devices',
        ),
        migrations.AddField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users_crud.UserProfil'),
        ),
        migrations.AddField(
            model_name='userprofil',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
