# Generated by Django 3.0.7 on 2020-06-24 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_crud', '0004_userprofil_keycloak_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofil',
            name='profil',
        ),
    ]
